name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region <AWS_REGION> --name nvidia-llm-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f eks/deployment.yaml
